---
write_files:
- content: |-
    BOOTPROTO=static
    NAME=eth0
    DEVICE=eth0
    TYPE=Ethernet
    ONBOOT=yes
    HWADDR=
    NETMASK=255.255.255.0
    IPADDR=1.1.1.1
    GATEWAY=1.1.1.254
  owner: root:root
  path: "/etc/sysconfig/network-scripts/ifcfg-eth0"
  permissions: '0644'
hostname: pyama-test001
users:
- name: 1
- name: 2
