_default: &def
  image: ubuntu-example001
  flavor: m1.small
  availability_zone: nova
pyama-test002.test.com:
  <<: *def
  tenant: test_tenant
  security_group :
    - 1
  networks:
    eth0:
      allowed_address_pairs:
        - "10.2.0.0"
      bootproto: static
      ip_address: 1.1.1.1/24
      gateway: 1.1.1.254
  user_data:
    hostname: pyama-test001
    users:
      - name: 1
  keypair: "example001"
